version: "3.1"
services:
    ssrapp:
        container_name: ssrapp
        build: .
        env_file: .env.development
        ports:
            - "3001:3001"
        volumes:
            - .:/usr/app
            - ./src:/usr/app/src
            - ./public:/usr/app/public
            - ./dist:/usr/app/dist
            - /usr/app/node_modules/bcrypt/
        links:
            - mongo
        networks:
            - webappnetwork
    mongo:
        image: mongo
        volumes:
            - ./mongo-volume/db:/data/db
            - ./mongo-volume/configdb:/data/configdb
        ports:
            - "27017:27017"
        networks:
            - webappnetwork

networks:
    webappnetwork:
        driver: bridge

volumes:
    mongodb:
    mongodb_config: