version: "3.1"
services:
    client:
        container_name: react_client
        build: ./client
        ports:
            - "3000:3000"
        volumes:
            - ./client/src:/usr/src/client/src
            - ./client/public:/usr/src/client/public
        links:
            - api
        networks:
            - webappnetwork
    api:
        container_name: node_api
        build: ./server
        ports:
            - "3001:3001"
        volumes:
            - ./server/src:/usr/src/server/src
            - ./server/dist:/usr/src/server/dist
        links:
            - mongo
        networks:
            - webappnetwork
    mongo:
        image: mongo
        volumes:
            - ./mongo-volume/db:/data/db
            - ./mongo-volume/configdb:/data/configdb
        ports:
            - "27017:27017"
        networks:
            - webappnetwork

networks:
    webappnetwork:
        driver: bridge

volumes:
    mongodb:
    mongodb_config: